# Generated by Django 4.0.5 on 2022-07-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
